name: Executar script de temperatures cada 6 minuts

on:
  schedule:
    - cron: '*/6 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codi
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·lar dependències
        run: |
          pip install requests

      - name: Executar script de temperatures
        run: |
          python temperatures_manresa.py
